### Decision Tree Algorithms on Credit Card Fraud Detection

In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import collections
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

df= pd.read_csv("/Users/navnigupta/Downloads/creditcard.csv")
pd.DataFrame(X)
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9   ...         V20       V21       V22       V23  \
0  0.098698  0.363787   ...    0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425   ...   -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654   ...    0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024   ...   -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739   ...    0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

### Calculating Accuracy for 10% of the dataset

In [21]:
df_new = df.sample(frac=0.1)
X = df_new.iloc[:,:-1]
y = df_new.iloc[:,-1]
df_new.loc[df_new['Class'] == 1]
df_new.head()

Time        V1        V2        V3        V4        V5        V6  \
271866  164788.0 -0.257399  0.940905  0.249592 -0.722777  0.404399 -0.903941   
3274      2822.0  1.175695  0.114254  0.494600  0.459372 -0.283004 -0.210279   
207786  136834.0 -1.281949 -0.880971  1.572680  0.473729 -0.510753  0.464929   
235011  148204.0 -0.475049  1.464148 -0.788750 -0.646772  0.593761 -0.627782   
153762  100004.0  1.970126  0.112834 -1.618409  1.432961  0.569400 -0.616603   

              V7        V8        V9  ...         V21       V22       V23  \
271866  0.858160 -0.044232 -0.094785  ...   -0.233322 -0.476642  0.087181   
3274   -0.157352  0.111676 -0.134934  ...   -0.185103 -0.562422  0.160712   
207786 -1.479577  0.906947  1.162604  ...    0.302678  1.342682  0.752444   
235011  0.583620  0.415496 -0.416506  ...   -0.261571 -0.666255  0.151984   
153762  0.371828 -0.255648  1.465385  ...   -0.074245  0.110816 -0.044404   

             V24       V25       V26       V27       V28  Amount  Class  
271866  0.062880 -0.482811  0.120201  0.344374  0.157091    0.99      0  
3274   -0.002423  0.096507  0.108889 -0.019816  0.004074    0.89      0  
207786 -0.251354 -1.191929  0.739599  0.144849  0.097928    0.00      0  
235011  0.678736 -0.366624  0.091093  0.210629  0.068806    9.98      0  
153762 -0.489382  0.392147 -0.522580 -0.059049 -0.081366   29.70      0  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
max_test_score = 0
MaxDepth=[]
TestScore=[]
TrainScore=[]
for i in range(1, 20):
    MaxDepth.append(i)
    clf_dt = DecisionTreeClassifier(max_depth=i)
    clf_dt.fit(X_train, y_train)
    train_score = clf_dt.score(X_train, y_train)
    test_score = clf_dt.score(X_test, y_test)
    TestScore.append(test_score)
    TrainScore.append(train_score)
    if test_score > max_test_score:
        related_train_score = train_score
        max_test_score = test_score
        max_i = i
        best_clf_dt = clf_dt
print("depth: ", max_i, "train: ", related_train_score)
print("depth: ", max_i, "test: ", max_test_score)

depth:  13 train:  1.0
depth:  13 test:  0.9991488456218747


In [8]:
clf_gini = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=13, max_features=None, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2, min_weight_fraction_leaf=0.0, presort=False, random_state=100, splitter='best')
clf_gini.fit(X_train, y_train)
clf_gini.score(X_train, y_train)

0.9995283513258568

In [9]:
y_pred_en_gini = clf_gini.predict(X_test)
y_pred_en_gini

array([0, 0, 0, ..., 0, 0, 0])

In [36]:
print(confusion_matrix(y_test, y_pred_en_gini))  
print("\t\tConfusion matrix for CART taking 10% of original data")
print(classification_report(y_test, y_pred_en_gini)) 

[[9386   22]
 [  14 9339]]
		Confusion matrix for CART taking 10% of original data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9408
           1       1.00      1.00      1.00      9353

   micro avg       1.00      1.00      1.00     18761
   macro avg       1.00      1.00      1.00     18761
weighted avg       1.00      1.00      1.00     18761



### Implementing Under Sampling
In this we have done under sampling to deal with the highly imbalanced dataset. So under sampling gives equal number of majority and minority class samples which are equal to number of minority class samples of the original dataset.
Here we have two classes fraudelent and non-fraudalent where fraudelent is the minority class represented by 1 and non-fraudalent is majority class represented by 0.

In [24]:
rus = RandomUnderSampler(random_state=0)
X_resampled_U, y_resampled_U = rus.fit_resample(X, y)
print(sorted(collections.Counter(y_resampled_U).items()))

[(0, 56), (1, 56)]


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled_U, y_resampled_U, test_size=0.33, random_state=42)

In [26]:
max_test_score = 0
MaxDepth=[]
TestScore=[]
TrainScore=[]
for i in range(1, 20):
    MaxDepth.append(i)
    clf_dt = DecisionTreeClassifier(max_depth=i)
    clf_dt.fit(X_train, y_train)
    train_score = clf_dt.score(X_train, y_train)
    test_score = clf_dt.score(X_test, y_test)
    TestScore.append(test_score)
    TrainScore.append(train_score)
    if test_score > max_test_score:
        related_train_score = train_score
        max_test_score = test_score
        max_i = i
        best_clf_dt = clf_dt
print("depth: ", max_i, "train: ", related_train_score)
print("depth: ", max_i, "test: ", max_test_score)

depth:  1 train:  0.9733333333333334
depth:  1 test:  0.9459459459459459


In [27]:
clf_gini = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1, max_features=None, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2, min_weight_fraction_leaf=0.0, presort=False, random_state=100, splitter='best')
clf_gini.fit(X_train, y_train)
print("The train score is",clf_gini.score(X_train, y_train))

The train score is 0.9733333333333334


In [28]:
y_pred_en_gini = clf_gini.predict(X_test)
y_pred_en_gini

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [37]:
print(confusion_matrix(y_test, y_pred_en_gini))  
print("\tClassification Report for CART with under sampling of 10% data")
print(classification_report(y_test, y_pred_en_gini)) 

[[9386   22]
 [  14 9339]]
	Classification Report for CART with under sampling of 10% data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9408
           1       1.00      1.00      1.00      9353

   micro avg       1.00      1.00      1.00     18761
   macro avg       1.00      1.00      1.00     18761
weighted avg       1.00      1.00      1.00     18761



### Implementing Oversampling
In this we have done over sampling to deal with the highly imbalanced dataset. So over sampling gives equal number of majority and minority class samples which are equal to number of majority class samples of the original dataset. Here we have two classes fraudelent and non-fraudalent where fraudelent is the minority class represented by 1 and non-fraudalent is majority class represented by 0. As the size of the dataset has been increased (double the size of original dataset) and hence taking a lot of time to implement decision tree algorithms,so to deal with this we have taken a sample having equal distribution of fraudelent and non fraudelent data.

In [30]:
X_resampled_O, y_resampled_O = SMOTE().fit_resample(X, y)
print(sorted(collections.Counter(y_resampled_O).items()))

[(0, 28425), (1, 28425)]


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled_O, y_resampled_O, test_size=0.33, random_state=42)

In [32]:
max_test_score = 0
MaxDepth=[]
TestScore=[]
TrainScore=[]
for i in range(1, 20):
    MaxDepth.append(i)
    clf_dt = DecisionTreeClassifier(max_depth=i)
    clf_dt.fit(X_train, y_train)
    train_score = clf_dt.score(X_train, y_train)
    test_score = clf_dt.score(X_test, y_test)
    TestScore.append(test_score)
    TrainScore.append(train_score)
    if test_score > max_test_score:
        related_train_score = train_score
        max_test_score = test_score
        max_i = i
        best_clf_dt = clf_dt
print("depth: ", max_i, "train: ", related_train_score)
print("depth: ", max_i, "test: ", max_test_score)

depth:  14 train:  0.9996849484103022
depth:  14 test:  0.998774052555834


In [33]:
clf_gini = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=14, max_features=None, max_leaf_nodes=None, min_samples_leaf=5, min_samples_split=2, min_weight_fraction_leaf=0.0, presort=False, random_state=100, splitter='best')
clf_gini.fit(X_train, y_train)
print("The train score is",clf_gini.score(X_train, y_train))

The train score is 0.9992123710257554


In [34]:
y_pred_en_gini = clf_gini.predict(X_test)
y_pred_en_gini

array([0, 0, 1, ..., 1, 0, 1])

In [38]:
print(confusion_matrix(y_test, y_pred_en_gini))  
print("\tClassification Report for CART with over sampling of 10% data")
print(classification_report(y_test, y_pred_en_gini)) 

[[9386   22]
 [  14 9339]]
	Classification Report for CART with over sampling of 10% data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9408
           1       1.00      1.00      1.00      9353

   micro avg       1.00      1.00      1.00     18761
   macro avg       1.00      1.00      1.00     18761
weighted avg       1.00      1.00      1.00     18761

